exclude: ['grunt.js', 'package.json', 'node_modules']
auto: true
markdown: rdiscount
pygments: true
production: true

title: 'Wu Jun'
author:
  name: 'WU Jun'
  email: 'epicwu@gmail.com'
  github: 'epicwu'

production_url: 'http://epicwu.github.com'

disqus:
  shortname: 'jakeharding'

JS_PATH: '/public/js'
CSS_PATH: '/public/style'
IMG_PATH: '/public/img'
