exclude: ['grunt.js', 'package.json', 'node_modules']
auto: true
markdown: kramdown
pygments: true

production: true

title: 'WU Jun'
author:
  name: 'WU Jun'
  email: 'epicwu@gmail.com'
  sina: 'EpicWU'
  github: 'epicwu'

production_url: 'http://epicwu.github.com'

disqus:
  shortname: 'epicwu'

JS_PATH: '/public/js'
CSS_PATH: '/public/style'
IMG_PATH: '/public/img'
